apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: sandbox-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.ajdev.com
      version: v1
  description: sandbox-operator
  displayName: sandbox-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ajgrande924
  - ajdev
  links:
  - name: Sandbox Operator
    url: https://sandbox-operator.domain
  maintainers:
  - email: ajgrande924@gmail.com
    name: ajgrande924
  maturity: alpha
  provider:
    name: ajgrande924
    url: https://github.com/ajgrande924
  version: 0.0.0
